// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum PlayerState {
  IDLE,
  IN_COMBAT,
  INJURED,
  DEAD,
  RESTING,
  TRAVELLING,
  FISHING
}

enum DurationType {
  SECONDS,
  MINUTES,
  HOURS,
  DAYS
}

enum EffectType {
  HEALING,
  DAMAGE,
  BUFF,
  DEBUFF,
  AOE_HEALING,
  AOE_DAMAGE
}

enum EquipmentSlot {
  HEAD,
  CHEST,
  LEGS,
  FEET,
  HANDS,
  NECK,
  RING1,
  RING2,
  WEAPON,
  SHIELD,
  OFFHAND
}

enum TargetType {
  SELF,
  PLAYER,
  ENEMY,
  ALLY,
  ALL
}

enum CurrencyType {
  GOLD,
  SILVER,
  THIRD_PARTY
}
