// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Config, ConfigData } from "./tables/Config.sol";
import { Player } from "./tables/Player.sol";
import { Level, LevelData } from "./tables/Level.sol";
import { Name } from "./tables/Name.sol";
import { State } from "./tables/State.sol";
import { LastAction } from "./tables/LastAction.sol";
