// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EffectType, DurationType, TargetType } from "../common.sol";
import { ConsumableData } from "../tables/Consumable.sol";

/**
 * @title IConsumableSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConsumableSystem {
  function app__createConsumable(
    uint256 id,
    uint256 itemId,
    uint256 charges,
    uint256 maxCharges,
    uint256 duration,
    EffectType effect,
    DurationType durationType,
    TargetType targetType
  ) external;

  function app__getConsumable(uint256 id) external view returns (ConsumableData memory);
}
