// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipmentSlot } from "../common.sol";
import { EquipmentData } from "../Tables/Equipment.sol";

/**
 * @title IEquipmentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEquipmentSystem {
  function app__createEquipment(
    uint256 id,
    EquipmentSlot slot,
    uint256 itemId,
    uint256 durability,
    uint256 maxDurability
  ) external;

  function app__getEquipment(uint256 id) external view returns (EquipmentData memory);
}
