// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Rarity } from "../common.sol";
import { ItemData } from "../tables/Item.sol";

/**
 * @title IItemSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemSystem {
  function app__createItem(uint256 id, Rarity rarity, uint256 level, uint256 salePrice) external;

  function app__getItem(uint256 id) external view returns (ItemData memory);
}
