// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITokenMinterSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokenMinterSystem {
  function app__mintGold(address to, uint256 amount) external;

  function app__getGoldAddress() external view returns (address);

  function app__getSilverAddress() external view returns (address);

  function app___getSilverAddress() external view returns (address);

  function app__mintSilver(address to, uint256 amount) external;

  function app__mintItem(address to, uint256 id) external;

  function app__getItemsAddress() external view returns (address);

  function app__mintAll(address to, uint256 amount) external;
}
